from BoaHancockBOT import (STRAWHATS, YONKO, ADMIRALS, WARLORDS, VICE_ADMIRALS, telethn)

IMMUNE_USERS = YONKO + VICE_ADMIRALS + ADMIRALS + WARLORDS + STRAWHATS

IMMUNE_USERS = list(YONKO) + list(VICE_ADMIRALS) + list(ADMIRALS) + list(
    WARLORDS) + list(STRAWHATS)
